name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version

      - name: Build the package
        run: python -m pip install .

      - name: Install cx_Freeze
        run: python -m pip install cx_Freeze
      - name: Freeze the package
        run: |
          cd extra/cx_Freeze
          if [ "$RUNNER_OS" == "Linux" ]; then
            python setup.py build
          elif [ "$RUNNER_OS" == "Windows" ]; then
            python setup.py bdist_msi
          elif [ "$RUNNER_OS" == "macOS" ]; then
            python setup.py bdist_dmg
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: Linux artifacts
          path: build
        if: runner.os == 'Linux'

      - uses: actions/upload-artifact@v2
        with:
          name: macOS artifacts
          path: build
        if: runner.os == 'macOS'

      - uses: actions/upload-artifact@v2
        with:
          name: Windows artifacts
          path: build
        if: runner.os == 'Windows'
