name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version

      - name: Build the package
        run: python -m pip install .

      - name: Check rjm_batch_submit command installed
        run: rjm_batch_submit --help

      - name: Check rjm_batch_wait command installed
        run: rjm_batch_wait --help

      - name: Install pyinstaller
        run: python -m pip install pyinstaller pip-licenses defopt
      - name: Build rjm_batch_submit
        run: pyinstaller -F --additional-hooks-dir=. rjm_batch_submit.py
        working-directory:  ./extra/pyinstaller
      - name: Build rjm_batch_wait
        run: pyinstaller -F --additional-hooks-dir=. rjm_batch_wait.py
        working-directory:  ./extra/pyinstaller
      - name: Dump license files
        run: python bundle_licenses.py dist/bundled_licenses.txt
        working-directory: ./extra/pyinstaller
      - name: Archive binaries
        uses: thedoctor0/zip-release@master
        with:
          type: zip
          directory: extra/pyinstaller/dist
          filename: RemoteJobManager-${{ runner.os }}.zip
      - uses: actions/upload-artifact@v2
        with:
          name: RemoteJobManager-${{ runner.os }}
          path: extra/pyinstaller/dist/RemoteJobManager-*.zip
