name: Documentation

on:
  push:
  pull_request:

jobs:
  pages:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: deployment
        name: Build documentation
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: ./docs
          pyproject_extras: dev
          python_version: "3.10"
          checkout: false
          publish: false
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ steps.deployment.outputs.artifact }}
          publish_branch: gh-pages
